REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400033, 'Tier 1 Research Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400063, 'Medium Raw-Hide Armor', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400064, 'Saltpeter', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400065, 'Tier 1 Gems', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400066, 'Tier 2 Gems', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400067, 'Rusty & Bronze Weapons', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400011, 'Heretic Runner Pouch', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400013, 'Fire Imp Specific', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400019, 'Fire Elemental Default', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400020, 'Fire Elemental Lavastorm', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400022, 'a rock dervish', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400054, 'Saltpeter', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400026, 'a fire drake', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400032, 'Small Raw-hide Armor', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400035, 'Caster Rusty Weapons', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400040, 'Bone Chips', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400037, 'a warbone monk', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400041, 'a warbone spearman', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400042, 'spearman shields', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400045, 'Basilisk Quest', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400046, 'Basilisk Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400047, 'Tier 3 Gems', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400055, 'Shadowed Man Weapons', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400056, 'Shadowed Man Misc', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400057, '97599___MAGELO-GEN', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400058, '97600___MAGELO-GEN', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400060, 'Rune of Scale Lavastorm', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400061, 'Tier 3 Research Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400062, 'Alligator Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400068, 'Testimony of Truth', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1400069, 'Glowing Torch', 0, 0, NULL, NULL);
