source ./lavastorm_classic/lootdrop_entries.sql
source ./lavastorm_classic/lootdrop.sql
source ./lavastorm_classic/loottable_entries.sql
source ./lavastorm_classic/loottable.sql
source ./lavastorm_classic/npc_faction.sql
source ./lavastorm_classic/npc_types.sql
source ./lavastorm_classic/spawn2.sql
source ./lavastorm_classic/spawnentry.sql
source ./lavastorm_classic/spawngroup.sql
source ./lavastorm_classic/zone_points.sql
source ./lavastorm_classic/grid.sql
source ./lavastorm_classic/grid_entries.sql
