source ./paw_original/lootdrop_entries.sql
source ./paw_original/lootdrop.sql
source ./paw_original/loottable_entries.sql
source ./paw_original/loottable.sql
source ./paw_original/npc_faction.sql
source ./paw_original/npc_types.sql
source ./paw_original/spawn2.sql
source ./paw_original/spawnentry.sql
source ./paw_original/spawngroup.sql
