source ./paw_prevamp/init.sql
source ./paw_prevamp/lootdrop_entries.sql
source ./paw_prevamp/lootdrop.sql
source ./paw_prevamp/loottable_entries.sql
source ./paw_prevamp/loottable.sql
source ./paw_prevamp/npc_faction.sql
source ./paw_prevamp/npc_types.sql
source ./paw_prevamp/spawn2.sql
source ./paw_prevamp/spawnentry.sql
source ./paw_prevamp/spawngroup.sql
source ./paw_prevamp/cleanup.sql
