REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300000, 'Spiderling Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300001, 'Spider Legs', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300002, 'Wolf Generic Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300003, 'Black Wolf Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300008, 'Snake Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300005, 'Pyre Beetle Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300006, 'Fire Beetle Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300007, 'Garter Snake Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300153, 'Medium Cloth Armor', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300114, 'Bone Chips', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300154, 'Rusty Weapons', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300151, 'Rusty Shields', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300016, 'Bear Generic Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300017, 'Large Snake Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300018, 'a black mamba', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300019, 'Giant Snake Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300020, 'Shadow Wolf Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300021, 'a basilisk hatchling', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300022, 'Large Spider Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300023, 'Willowisp Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300069, 'Crushbone Orc Parts', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300025, 'a deathfist scout', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300072, 'Medium & Large Cloth Armor', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300073, 'Brick of Crude Bronze', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300147, 'Cracked Helm of the Lifebringer', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300162, 'Priest Rusty Weapons', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300170, 'Dragoon Dirk 15', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300171, 'Long Sword', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300033, 'Tier 5 Research Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300113, 'Calcified Skeleton Parts', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300039, 'a deathfist templar', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300040, 'Tier 2 Gems', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300145, 'Blood Drenched Cloak', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300045, 'Undead Steward Pages', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300048, 'an ash drakeling', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300052, 'Petrified Bones', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300059, 'Shadowed Man Weapons', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300060, 'Shadowed Man Misc', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300167, 'Nektulos Halflings', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300142, 'First Riddle for the Troll', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300169, 'Halfling Bones', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300166, 'Matted Halfling Hide', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300070, 'a deathfist legionnaire', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300096, 'Bronze Long Sword', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300079, 'Tier 2 Research Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300097, 'Tier 1 Research Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300101, 'Medium Cloth & Raw-hide Armor', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300102, 'a rotting citizen', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300108, 'a darkwater piranha', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300110, 'Fish Drops', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300121, 'Master Whoopal', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300127, 'Snitch', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300168, 'Caster Rusty Weapons', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300149, 'Zombie Skin', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300155, 'Embalming Dust', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300164, 'Apprentice Robe', 0, 0, NULL, NULL);
REPLACE INTO `lootdrop` (`id`, `name`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES (1300165, 'Kirak Vil', 0, 0, NULL, NULL);
