REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18700', 'a_bat', '1', '34', '1', '1', '16', '0', '2', '3');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18701', 'gnoll_prisoner', '2', '39', '1', '1', '28', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18702', 'gnoll_prisoner', '3', '39', '1', '1', '47', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18703', 'gnoll_prisoner', '4', '39', '1', '1', '68', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18704', 'a_gnoll', '4', '39', '1', '1', '80', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18705', 'a_gnoll', '5', '39', '1', '1', '105', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18706', 'a_gnoll', '6', '39', '1', '1', '131', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18707', 'a_gnoll', '7', '39', '1', '1', '157', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18708', 'a_gnoll', '8', '39', '1', '1', '183', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18709', 'a_gnoll', '9', '39', '1', '1', '210', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18710', 'a_large_snake', '4', '37', '1', '1', '80', '0', '2', '5');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18711', 'a_large_snake', '5', '37', '1', '1', '99', '0', '2', '5');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18712', 'a_large_snake', '6', '37', '1', '1', '120', '0', '2', '5');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18713', 'a_Splitpaw_gnoll', '4', '39', '1', '1', '80', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18714', 'a_Splitpaw_gnoll', '5', '39', '1', '1', '104', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18715', 'a_Splitpaw_gnoll', '6', '39', '1', '1', '129', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18716', 'a_Splitpaw_gnoll', '7', '39', '1', '1', '154', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18717', 'a_Splitpaw_gnoll', '8', '39', '1', '1', '180', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18718', 'a_skeleton', '5', '60', '1', '1', '100', '0', '2', '8');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18719', 'a_Splitpaw_guard', '6', '39', '1', '1', '140', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18720', 'a_Splitpaw_guard', '7', '39', '1', '1', '166', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18721', 'a_Splitpaw_guard', '8', '39', '1', '1', '194', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18722', 'a_Splitpaw_guard', '9', '39', '1', '1', '221', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18723', 'a_Splitpaw_guard', '10', '39', '1', '1', '249', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18724', 'a_zombie', '6', '70', '1', '1', '150', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18725', 'a_giant_snake', '7', '37', '1', '1', '170', '0', '2', '7');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18726', 'a_giant_snake', '8', '37', '1', '1', '189', '0', '2', '7');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18727', 'a_giant_snake', '9', '37', '1', '1', '210', '0', '2', '7');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18728', 'a_gnoll_shaman', '8', '39', '1', '1', '141', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18729', 'a_gnoll_shaman', '9', '39', '1', '1', '162', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18730', 'a_Splitpaw_shaman', '8', '39', '1', '1', '141', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18731', 'a_Splitpaw_shaman', '9', '39', '1', '1', '161', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18732', 'a_Splitpaw_shaman', '10', '39', '1', '1', '183', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18733', 'a_Splitpaw_noble', '10', '39', '1', '1', '250', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18734', 'a_Splitpaw_noble', '11', '39', '1', '1', '279', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18735', 'a_Splitpaw_noble', '12', '39', '1', '1', '309', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18736', 'Gelatinous_Cube', '12', '31', '1', '1', '310', '0', '2', '4');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18737', 'Gelatinous_Cube', '13', '31', '1', '1', '329', '0', '2', '4');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender, size) VALUES ('18738', 'Gelatinous_Cube', '14', '31', '1', '1', '350', '0', '2', '4');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18739', 'a_Splitpaw_commander', '12', '39', '1', '1', '330', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18740', 'a_Splitpaw_commander', '13', '39', '1', '1', '350', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18741', 'Brother_Gruff', '14', '39', '1', '1', '280', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18742', 'Brother_Gruff', '15', '39', '1', '1', '300', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18743', 'Shaman_Lenrel', '14', '39', '1', '1', '280', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18744', 'Ghanex_Drah', '15', '39', '1', '1', '225', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18745', 'Ghanex_Drah', '16', '39', '1', '1', '245', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18746', 'a_Splitpaw_captain', '15', '39', '1', '1', '430', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18747', 'a_Splitpaw_captain', '16', '39', '1', '1', '448', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18748', 'Shaman_Ren`Rex', '15', '39', '1', '1', '455', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18749', 'Shaman_Ren`Rex', '16', '39', '1', '1', '472', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18750', 'Shaman_Ren`Rex', '17', '39', '1', '1', '490', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18751', 'High_Shaman_Grisok', '17', '39', '1', '1', '490', '0', '2');
REPLACE INTO npc_types (id, name, level, race, class, bodytype, hp, mana, gender) VALUES ('18752', 'Brother_Hayle', '24', '39', '1', '1', '884', '0', '2');
